[package]
name = "duplex"
version = "0.1.0"
authors = ["Ze'ev Klapow <zklapow@gmail.com>"]

[dependencies]
log = "^0.3"
env_logger = "^0.3"
clap = "^2.23"
futures = "^0.1"
tokio-core = "^0.1"
tokio-io = "^0.1"
tokio-proto = "^0.1"
tokio-service = "^0.1"
bytes = "^0.4"
chrono = "^0.3"
